parameters:
#    project_back.example.class: Project\BackBundle\Example

services:
#    project_back.example:
#        class: %project_back.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
