# src/Acme/UserBundle/Resources/config/doctrine/User.orm.yml
Project\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255